replicaCount: 1

image:
  repository: postgres
  tag: "15.3"
  pullPolicy: IfNotPresent

postgresUser: demo_user
postgresPassword: demo_password
postgresDatabase: demo_db

service:
  type: ClusterIP
  port: 5432

initSqlConfigMapName: init-sql-config

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"


persistence:
  enabled: false
# Active la persistance des données si tu veux garder la base entre redéploiements
# storageClass: "standard"
# accessMode: ReadWriteOnce
# size: 1Gi
