apiVersion: v1
kind: Service
metadata:
  name: postgres-demo
  labels:
    app: postgres-demo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres-demo
